import argparse
from pathlib import Path
import xml.etree.ElementTree as ET
import minify_html
import re

content_dir = Path("content/")
output_dir = Path("output/")

parser = argparse.ArgumentParser()
parser.add_argument("action", help="Action you would like to perform. Supported actions: build.")
args = parser.parse_args()

if args.action == "build":
    for file in content_dir.iterdir():
        template = ""
        with open("template.html", "r") as f:
            template = f.read()

        template = "<!--OUTPUT FILE GENERATED BY LANGPEDIA SSG-->\n" + template
        out = "<br>"
        sidebar = ""

        tree = ET.parse(file)
        root = tree.getroot()

        for elem in root.iter():
            print(elem.tag)
            print(elem.text.strip())
            print(elem.attrib)

            if elem.tag == "title":
                out += "<title>" + elem.text.strip() + " - Langpedia</title>"
            elif elem.tag == "tableofcontents":
                for i in elem.text.strip().split("\\br\\"):
                    sidebar += "<a href='#" + i.lower().strip().replace("\\sp\\", "").replace("\\br\\", "") + "'>" + i + "</a>"
            elif elem.tag == "p":
                out += "<p>" + elem.text.strip() + "</p>"

        out = out.replace("\\br\\", "<br>").replace("\\sp\\", "&nbsp;")
        sidebar = sidebar.replace("\\br\\", "<br>").replace("\\sp\\", "&nbsp;")

        content = file.read_text(encoding="utf-8", errors="ignore")
        output_file = output_dir / (file.name.replace(".lp.xml", ".html"))
        output_file.write_text(minify_html.minify(template.replace("{{content}}", out).replace("{{sidebar}}", sidebar), minify_js=True, minify_css=True).replace("\u00A0", "&nbsp;"), encoding="utf-8")