import argparse
from pathlib import Path
from lxml import etree
import re
import os
import citationlib
import platform
from urllib.parse import quote_plus
import requests
import json

content_dir = Path("content/")
output_dir = Path("output/")

parser = argparse.ArgumentParser()
parser.add_argument("action", help="Action you would like to perform. Supported actions: build, run.")
parser.add_argument("--root_url", nargs="?", const="/", type=str)
parser.add_argument("--skip-cite", nargs="?", const="no", type=str)
args = parser.parse_args()

if args.action == "build" or args.action == "run":
    totalarticles = len(list(content_dir.iterdir()))
    print(str(totalarticles) + " total files to compile.")

    for file in content_dir.iterdir():
        template = ""
        with open("template.html", "r") as f:
            template = f.read()

        template = "<!--OUTPUT FILE GENERATED BY LANGPEDIA SSG-->\n" + template
        out = "<br>"
        sidebar = ""
        
        tree = etree.parse(file)
        root = tree.getroot()

        for elem in root.iter():
            if elem.text is not None:
                text = elem.text.strip()
            else:
                text = ""           

            if elem.tag == "rightbox":
                out += "<div style='float: right;padding:20px;' class='rightbox'>"
                for child in elem:
                    if child.tag == "img":
                        out += "<img src=\"" + child.text.strip() + "\">"
                    elif child.tag == "br":
                        out += "<br>"
                    elif child.tag == "h1":
                        out += "<h1>" + child.text.strip() + "</h1>"
                    elif child.tag == "p":
                        out += "<p>" + child.text.strip() + "</p>"
                    elif child.tag == "link":
                        out += "<a href=\"" + child.attrib["where"] + "\">" + child.text.strip() + "</a>"
                out += "</div>"
                continue
            
            if elem.getparent() is not None and elem.getparent().tag == "html":
                continue

            if elem.getparent() == None or elem.getparent().tag != "rightbox":
                if elem.tag == "html" and "html" in elem.attrib:
                    out += elem.attrib["html"]
                elif elem.tag == "html":
                    out += text
                elif elem.tag == "htmltag":
                    out += "<" + text + ">"
                elif elem.tag == "htmltagend":
                    out += "</" + text + ">"
                elif elem.tag == "title":
                    out += "<title>" + text + " - Langpedia</title>"
                elif elem.tag == "tableofcontents":
                    for i in text.split("\\br\\"):
                        sidebar += "<a href='#" + i.lower().strip().replace("\\sp\\", "").replace("\\br\\", "").replace(" ", "_") + "'>" + i + "</a>"
                elif elem.tag == "p":
                    out += "<p>" + text + "</p>"
                elif elem.tag == "h1":
                    if "name" in elem.attrib:
                        out += "<h1 id=\"" + elem.attrib["name"] + "\">" + text + "</h1>"
                    else:
                        out += "<h1>" + text + "</h1>"
                elif elem.tag == "h2":
                    if "name" in elem.attrib:
                        out += "<h2 id=\"" + elem.attrib["name"] + "\">" + text + "</h2>"
                    else:
                        out += "<h2>" + text + "</h2>"
                elif elem.tag == "h3": 
                    if "name" in elem.attrib:
                        out += "<h3 id=\"" + elem.attrib["name"] + "\">" + text + "</h3>"
                    else:
                        out += "<h3>" + text + "</h3>"
                elif elem.tag == "br":
                    out += "<br>"
                elif elem.tag == "link":
                    where = elem.attrib["where"]
                    if where.endswith(".lp.xml"):
                        where = where.replace(".lp.xml", ".html")
                    out += "<a href=\"" + where + "\">" + text + "</a>"
                elif elem.tag == "span":
                    out += "<span>" + text + "</span>"
                elif elem.tag == "i":
                    out += "<i>" + text + "</i>"
                elif elem.tag == "cite":
                    if platform.system() == "Windows":
                        print("Warning: Citations are not supported on Windows, continuing without.")

                    if args.skip_cite != "yes":
                        try:
                            citation = citationlib.create_citation(
                                text,
                                style=citationlib.Style.APA,
                                output_format=citationlib.Format.HTML
                            )
                            out += citation
                        except (ValueError, citationlib.exceptions.CitationError):
                            out += "<p>" + text + " (citations not supported on Windows)</p>"
                    else:
                        out += "<p>" + text + " (citation skip option enabled)</p>"
                elif elem.tag == "code":
                    out += "<pre><code>" + text.replace("[LT]", "&lt;").replace("[GT]", "&gt;") + "</code></pre>"
                elif elem.tag == "lpml": pass
                else:
                    print("Unknown tag:", elem.tag)

        out = out.replace("\\br\\", "<br>").replace("\\sp\\", "&nbsp;")
        sidebar = sidebar.replace("\\br\\", "<br>").replace("\\sp\\", "&nbsp;")

        if args.root_url is None:
            root_url = "/"
        else:
            root_url = args.root_url
        
        for f in content_dir.iterdir():
            page = f.name.replace(".lp.xml", "")
            out = out.replace("\\page:" + page + "\\", "<a href=\"" + root_url + page + ".html\">" + page + "</a>")
            out = out.replace("\\page:" + page.upper() + "\\", "<a href=\"" + root_url + page + ".html\">" + page.upper() + "</a>")

        content = file.read_text(encoding="utf-8", errors="ignore")
        output_file = output_dir / (file.name.replace(".lp.xml", ".html"))
        output_file.write_text(
            (
                template
                    .replace("{{content}}", out)
                    .replace("{{sidebar}}", sidebar)
            )
                .replace("{{ROOT}}", root_url)
                .replace("{{totalarticlecount}}", str(totalarticles)),
        encoding="utf-8")

    if args.action == "run":
        os.system("python -m http.server -d output")